Bombelka/ZaUsmiechBombelka/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from users.forms import MyAuthForm, MyResetForm
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/<username>/', user_views.profile, name='profile'),
    path('profile/edit', user_views.profile_editor, name='profile-editor'),
    path('register/', user_views.register, name='register'),
    path('users/follow/', user_views.user_follow, name='user_follow'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html', authentication_form=MyAuthForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', user_views.MyPasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', user_views.MyPasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('', include('blog.urls')),
    path('market/', include('market.urls')),
    path('actions/', include('actions.urls')),
    path('messages/', include('messanger_system.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bombelka/blog/urls.py
from django.urls import path
from .views import (PostDetailView,
                    PostCreateView,
                    PostUpdateView,
                    PostDeleteView,
                    CommentCreateView)
from . import views

urlpatterns = [
    path('', views.home, name='blog-home'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/<int:pk>/update', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post-delete'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/comment/', CommentCreateView.as_view(), name='add_comment_to_post'),
    path('about/', views.about, name='blog-about'),
    path('likepost/', views.likePost, name='likepost'),
    path('post/<username>/', views.user_posts, name='user-posts'),
]

Bombelka/users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.urls import reverse

class Profile(models.Model):
    SEX_TAG_CHOISE = [('Boy','dla chłopca'),('Girl', 'dla dziewczynki'), ('Unisex', 'zarówno dla chłopca jaki i dziewczynki')]
    AGE_TAG_CHOISE =[(1,'< 1 miesiąca'),(2,'< 3 miesiący'),(3,'< 6 miesięcy'),(4,'< 1 rok'),(5,'< 1.5 roku'),(6,'< 2 lat'),(7,'Ponad 2 lat')]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    description = models.TextField(default='Brak opisu')
    interested_sex_tag = models.CharField(max_length=6, choices = SEX_TAG_CHOISE, default='Unisex')
    interested_age_tag = models.IntegerField(choices=AGE_TAG_CHOISE, default=1)
    sold_sex_tag = models.CharField(max_length=6, choices = SEX_TAG_CHOISE, default='Unisex')
    sold_age_tag = models.IntegerField(choices=AGE_TAG_CHOISE, default=1)

    def __str__(self):
        return f'{self.user.username} Profile'

    def get_absolute_url(self):
        return reverse('profile', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
            super().save(*args, **kwargs)
            img = Image.open(self.image.path)
            if img.height > 300 or img.width > 300:
                output_size = (300,300)
                img.thumbnail(output_size)
                img.save(self.image.path)

class Contact(models.Model):
    user_from = models.ForeignKey(User, on_delete=models.CASCADE, related_name='rel_from_set')
    user_to = models.ForeignKey(User, on_delete=models.CASCADE, related_name='rel_to_set')
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return '{} follows {}'.format(self.user_from, self.user_to)



User.add_to_class('following',
                  models.ManyToManyField('self',
                                         through=Contact,
                                         related_name='followers',
                                         symmetrical=False))


User.add_to_class('total_followers',
                  models.PositiveIntegerField(db_index=True, default=0))

Bombelka/users/forms.py
from .models import Profile
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


SEX_TAG_CHOISE = [('Boy','dla chłopca'),('Girl', 'dla dziewczynki'), ('Unisex', 'zarówno dla chłopca jaki i dziewczynki')]
AGE_TAG_CHOISE =[(1,'< 1 miesiąca'),(2,'< 3 miesiący'),(3,'< 6 miesięcy'),(4,'< 1 rok'),(5,'< 1.5 roku'),(6,'< 2 lat'),(7,'Ponad 2 lat')]


class MyAuthForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username','password']

    def __init__(self, *args, **kwargs):
        super(MyAuthForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget = forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'})
        self.fields['username'].label = False
        self.fields['password'].widget = forms.PasswordInput(attrs={'class': 'form-control', 'placeholder':'Password'})
        self.fields['password'].label = False

class MyResetForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['email']

    def __init__(self, *args, **kwargs):
        super(MyResetForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget = forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Email'})
        self.fields['email'].label = False

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={'placeholder': 'Email', 'class': 'form-control'}))
    interested_sex_tag = forms.ChoiceField(widget=forms.Select(attrs={'class':"form-control"}),label='', choices=SEX_TAG_CHOISE)
    interested_age_tag = forms.ChoiceField(widget=forms.Select(attrs={'class':"form-control"}),label='', choices=AGE_TAG_CHOISE)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        widgets = {
            'username': forms.fields.TextInput(attrs={'placeholder': 'Username', 'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        self.fields['password1'].widget = forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'})
        self.fields['password2'].widget = forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password confirmation'})

        for fieldname in ['username', 'email','password1', 'password2', 'interested_sex_tag', 'interested_age_tag']:
            self.fields[fieldname].help_text = None
            self.fields[fieldname].label = ""


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={'placeholder': 'Email', "class":"form-control"}))
    username = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder': 'Username', "class":"form-control"}))

    class Meta:
        model = User
        fields = ['username', 'email']

    def __init__(self, *args, **kwargs):
        super(UserUpdateForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'email']:
            self.fields[fieldname].help_text = None


class ProfileUpdateForm(forms.ModelForm):
    description = forms.CharField(label='',widget=forms.Textarea(attrs={"rows":"6", "class":"form-control"}))
    interested_sex_tag = forms.ChoiceField(widget=forms.Select(attrs={'class':"form-control-sm mx-sm-1"}), label='', choices=SEX_TAG_CHOISE)
    interested_age_tag = forms.ChoiceField(widget=forms.Select(attrs={'class':"form-control-sm mx-sm-1"}),label='', choices=AGE_TAG_CHOISE)
    sold_sex_tag = forms.ChoiceField(widget=forms.Select(attrs={'class':"form-control-sm mx-sm-1"}),label='', choices=SEX_TAG_CHOISE)
    sold_age_tag = forms.ChoiceField(widget=forms.Select(attrs={'class':"form-control-sm mx-sm-1"}),label='', choices=AGE_TAG_CHOISE)

    class Meta:
        model = Profile
        fields = ['image', 'description', 'interested_sex_tag', 'interested_age_tag', 'sold_sex_tag', 'sold_age_tag']

Bombelka/users/views.py
from .forms import (UserRegisterForm,
                    UserUpdateForm,
                    ProfileUpdateForm)
from .models import Contact
from actions.utils import create_action
from blog.models import Post
from django import forms
from django.contrib import messages
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import (render,
                            redirect,
                            get_object_or_404)
from django.views.decorators.http import require_POST
from market.models import Product


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.profile.interested_sex_tag = form.cleaned_data.get('interested_sex_tag')
            user.profile.interested_age_tag = form.cleaned_data.get('interested_age_tag')
            user.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}! You are able to log in!')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request,'users/register.html', {'form': form})


@login_required
def profile(request, username):
    user = get_object_or_404(User,
                            username=username,
                            is_active=True)
    posts = Post.objects.filter(author=user).order_by('-date_posted')[:3]
    products = Product.objects.filter(author=user).order_by('-date_posted')[:3]
    context = {
        'posts': posts,
        'products': products,
        'user': user,
    }
    return render(request, 'users/profile.html', context)


@login_required
def profile_editor(request):
    username = request.user.username
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST,
                                instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                    request.FILES,
                                    instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            new_username = u_form.cleaned_data['username']
            messages.success(request, f'Twój profil został zaktualizowany')
            return redirect('profile', new_username)
        else:
            print(u_form.errors)
            print(p_form.errors)
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
    context = {
        'u_form': u_form,
        'p_form': p_form,
    }
    return render(request, 'users/profile_editor.html', context)


@require_POST
@login_required
def user_follow(request):
    user_id = request.POST.get('id')
    action = request.POST.get('action')
    if user_id and action:
        try:
            user = User.objects.get(id=user_id)
            if action == 'follow':
                Contact.objects.get_or_create(user_from=request.user,
                                            user_to=user)
                create_action(request.user, 'zaczął obserwować', user)
            else:
                Contact.objects.filter(user_from=request.user,
                                    user_to=user).delete()
            return JsonResponse({'status': 'ok'})
        except User.DoesNotExist:
            return JsonResponse({'status': 'ko'})
    return JsonResponse({'status': 'ko'})


class MyPasswordResetView(PasswordResetView):
    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        form = super(MyPasswordResetView, self).get_form(form_class)
        form.fields['email'].widget = forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Email'})
        form.fields['email'].lable = ''
        return form

class MyPasswordResetConfirmView(PasswordResetConfirmView):
    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        form = super(MyPasswordResetConfirmView, self).get_form(form_class)
        form.fields['new_password1'].widget = forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'New password'})
        form.fields['new_password1'].label = False
        form.fields['new_password1'].help_text = None
        form.fields['new_password2'].widget = forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password confirmation'})
        form.fields['new_password2'].label = False
        form.fields['new_password2'].help_text = None
        return form

Bombelka/users/templates/users/login.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags%}
{% block content %}
<div class="content-section">
    <div class="d-flex justify-content-center">
        <form method="POST" enctype="multipart/form-data">
            <legend class="d-flex justify-content-center"> Zaloguj się</legend>
            {% csrf_token %}
            <div class="form-group">
                <div class="form-row">
                    <div class="form-group col mb-2">
                        {{ form.username|as_crispy_field }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col ">
                        {{ form.password|as_crispy_field }}
                        <a href="{% url 'password_reset' %}"class="float-right"><small>Zapomniałeś hasła?</small></a>
                    </div>
                </div>
                <button class="btn btn-sample btn-block" type="submit"><span style="font-size:smaller;">Zaloguj się </span></button>
            </div>
            <div class="d-flex justify-content-center">
                <small class="text-muted"> Nie masz konta?<a class="ml-2" href="{% url 'register' %}">Zarejestruj się</a></small>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

Bombelka/users/templates/users/logout.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="content-section">
        <div class="media-body">
            <div class="d-flex justify-content-center mb-4">
                <h2>Wylogowanie zakończono pomyślnie!</h2>
            </div>
            <div class="d-flex justify-content-center mt-5">
                <a href="{% url 'login' %}"><button class="btn btn-sample btn-block">Zaloguj się ponownie</button></a>
            </div>
        </div>
    </div>
{% endblock content %}

Bombelka/users/templates/users/password_reset.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags%}
{% block content %}
<div class="content-section">
    <div class="d-flex justify-content-center">
        <form method="POST" enctype="multipart/form-data">
            <legend class="d-flex justify-content-center"> Zresetuj hasło</legend>
            {% csrf_token %}
            <div class="form-group">
                <div class="form-row">
                    <div class="form-group col mb-2">
                        {{ form.email }}
                    </div>
                </div>
                <button class="btn btn-sample btn-block" type="submit"><span style="font-size:smaller;">Resetuj hasło</span></button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

Bombelka/users/templates/users/password_reset_complete.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="alert alert-success">
        <p>Hasło zrestartowane.</p>
        <a href="{% url 'login' %}">Zaloguj się ponownie</a>
    </div>
{% endblock content %}

Bombelka/users/templates/users/password_reset_confirm.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags%}
{% block content %}
<div class="content-section">
    <div class="d-flex justify-content-center">
        <form method="POST" enctype="multipart/form-data">
            <legend class="d-flex justify-content-center"> Zresetuj hasło</legend>
            {% csrf_token %}
            <div class="form-group">
                <div class="form-row">
                    <div class="form-group col mb-2">
                        {{ form.new_password1|as_crispy_field }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col mb-2">
                        {{ form.new_password2|as_crispy_field }}
                    </div>
                </div>
                <button class="btn btn-sample btn-block" type="submit"><span style="font-size:smaller;">Resetuj hasło</span></button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

Bombelka/users/templates/users/password_reset_done.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="alert alert-success">
        <p>Hasło zrestartowane.</p>
        <p>Sprawdź swoją skrzynkę e-mail</p>
    </div>
{% endblock content %}

Bombelka/users/templates/users/profile.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <div class="media-body">
        <div class="d-flex align-content-start flex-wrap mb-3">
            <div class="mr-auto p-2">
                <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
            </div>
            <div class="p-2">
                <h1>{{ user.username }}</h1>
                <p class="text-secondary">{{ user.email }}</p>
                {% if  user.username == request.user.username %}<a class="btn btn-sample btn-block" href="{% url 'profile-editor' %}">Edytuj profil</a>{% endif %}
            </div>
        </div>
        <div class="d-flex bd-highlight mb-3">
            {% with total_followers=user.followers.count %}
                {% if not  user.username == request.user.username %}
                    <div class="mr-auto p-2 bd-highlight">
                        <span class="count">
                            <span class="total">{{ total_followers }}</span> <a href="#">Obserwujący{{ total_followers|pluralize:"ch" }}</a>
                        </span>
                    </div>
                    <div class="p-2 bd-highlight">
                        <a href="{% url "user_follow" %}" data-id="{{ user.id }}" data-action="{% if request.user in user.followers.all %}un{% endif %}follow" class="follow btn btn-sample btn-block">
                            {% if request.user not in user.followers.all %}
                                Follow
                             {% else %}
                                Unfollow
                            {% endif %}
                        </a>
                    </div>
                {% else %}
                    <div class="mr-auto p-2 bd-highlight">
                        <span class="count">
                                Masz <span class="total">{{ total_followers }}</span> <a href="#">Obserwujący{{ total_followers|pluralize:"ch" }}</a>
                        </span>
                    </div>
                {% endif %}
            {% endwith %}
        </div>
    </div>
</div>

<div class="content-section">
    <div class="media-body">
        <h3>{% if  user.username == request.user.username %}Mój opis:{% else %}O mnie:{% endif %}</h3>
        <p>Aktualnie poszukuje ubranek <strong>{{user.profile.get_interested_sex_tag_display}}</strong> w wieku <strong>{{user.profile.get_interested_age_tag_display}}</strong>. Dodawane przeze mnie produkty to głównie ubranka przeznaczone <strong>{{user.profile.get_sold_sex_tag_display}}</strong> w wieku <strong>{{user.profile.get_sold_age_tag_display}}</strong></p>
        <p class="lead">{{ user.profile.description|linebreaks }}</p>
    </div>
</div>

<div class="content-section">
    <div class="media-body">
        <h3>{% if  user.username == request.user.username %}Moje przedmioty{% else %}Przedmioty użytkownika {{user.username}}{% endif %}:</h3>
        <div class="d-flex flex-column bd-highlight mb-3">
            {% for product  in products %}
                <div class="row justify-content-center">
                    <div class="article-metadata">
                        <a href="{% url 'product-detail' product.id %}"><img class="img-fluid" alt="Responsive image" src="{{ product.photo_1.url }}"></a>
                    </div>
                </div>
            {% empty %}
                <p class="lead">{% if  user.username == request.user.username %}
                                Nie dodałeś jeszcze żadnego produktu
                                {%else%}
                                Użytkownik {{ user.username}} nie dodał jeszcze żadnego produktu
                                {% endif %}
                </p>
            {% endfor %}
        </div>
        {% if  products %}<a class="btn btn-sample btn-block" href="{% url 'user-products' user.username %}">Zobacz wszystkie</a>{% endif %}
    </div>
</div>

<div class="content-section">
    <div class="media-body">
        <h3>{% if  user.username == request.user.username %}Moje posty{% else %}Posty użytkownika {{user.username}}{% endif %}:</h3>
        {% for post  in posts %}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <div class="d-flex align-content-end flex-wrap" >
                        <div class="p-2 mr-auto">
                            <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
                        </div>
                        <div class="p-2 mr-auto">
                            <a class="mr-2" href="{% url 'profile' post.author.username %}">{{ post.author }}</a>
                            <br>
                            <small class="text-muted mr-2">{{ post.date_posted|date:"d F Y" }}</small>
                        </div>
                    </div>
                </div>
                <h2><a class="article-title" href="{% url 'post-detail' post.id%}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
                <div class="d-flex align-content-end flex-wrap mt-1" >
                    <div class="p-2 mr-auto">
                        <p class="article-content">Komentarze ({{ post.comments.count }})</p>
                    </div>
                    <div class="p-2 mr-auto">
                        <p class="article-content">Polubień ({{ post.users_like.count}})</p>
                    </div>
                </div>
            </div>
        </article>
        {% empty %}
                <p class="lead">{% if  user.username == request.user.username %}
                                Nie dodałeś jeszcze żadnego postu
                                {%else%}
                                Użytkownik {{ user.username}} nie dodał jeszcze żadnego postu
                                {% endif %}
                </p>
        {% endfor %}
        {% if posts %}<a class="btn btn-sample btn-block" href="{% url 'user-posts' user.username %}">Zobacz wszystkie</a>{% endif %}
    </div>
</div>
{% endblock content %}

{% block domready %}
$('a.follow').click(function(e){
        e.preventDefault();
        $.post('{% url "user_follow" %}',
            {
                id: $(this).data('id'),
                action: $(this).data('action')
            },
            function(data){
                if (data['status'] == 'ok')
                {
                    var previous_action = $('a.follow').data('action');

                    // toggle data-action
                    $('a.follow').data('action', previous_action == 'follow' ? 'unfollow' : 'follow');
                    // toggle link text
                    $('a.follow').text(previous_action == 'follow' ? 'Unfollow' : 'Follow');

                    // update total followers
                    var previous_followers = parseInt($('span.count .total').text());
                    $('span.count .total').text(previous_action == 'follow' ? previous_followers + 1 : previous_followers - 1);
                }
        });
    });
{% endblock %}

Bombelka/users/templates/users/profile_editor.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <legend class="border-bottom mb-4">Profile Editor</legend>
        <div class="form-row">
            <div class="form-group col mb-2">
                {{ u_form.username|as_crispy_field }}
            </div>
            <div class="form-group col mb-2">
                {{ u_form.email|as_crispy_field }}
            </div>
        </div>
        <br>
        <div class="form-inline ml-1 mb-1 mt-1 mr-1">
                Aktualnie poszukuje ubranek {{ p_form.interested_sex_tag|as_crispy_field }} w wieku {{ p_form.interested_age_tag|as_crispy_field }}
        </div>
        <div class="form-inline ml-1 mb-4 mt-1 mr-1">
                Dodawane przeze mnie produkty ubranka przeznaczone {{ p_form.sold_sex_tag|as_crispy_field }} w wieku {{ p_form.sold_age_tag|as_crispy_field }}
        </div>
        <div class="form-row bt-2">
            <div class="form-group col mb-2">
                {{ p_form.description|as_crispy_field }}
            </div>
        </div>
        <br>
        <div class="form-row">
            <img class="img-fluid mr-2 ml-2" alt="Responsive image" src="{{ user.profile.image.url }}">
            <div class="form-group col mb-2 mr-10 ml-2">
                {{ p_form.image|as_crispy_field }}
            </div>
        </div>
    </div>
    <div class="form-group">
        <button class="btn btn-sample btn-block" type="submit">Zaktualizuj Profil</button>
    </div>
</form>
{% endblock %}

Bombelka/users/templates/users/register.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags%}
{% block content %}
<div class="content-section">
    <div class="d-flex justify-content-center">
        <form method="POST" enctype="multipart/form-data">
            <legend class="d-flex justify-content-center"> Dołącz Dziś</legend>
            {% csrf_token %}
            <div class="form-group">
                <div class="form-row">
                    <div class="form-group col mb-2">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col mb-2">
                        {{ form.email }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col mb-2">
                        {{ form.password1 }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col mb-2">
                        {{ form.password2 }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col mb-2">
                        <p><strong>Poszukuję ubranek:</strong></p>
                        {{ form.interested_sex_tag}}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col mb-2">
                        <p><strong>w wieku:</strong></p>
                        {{ form.interested_age_tag }}
                    </div>
                </div>
            </div>
            <div class="form-group">
                <button class="btn btn-sample btn-block" type="submit"><span style="font-size:smaller;">Zapisz</span></button>
            </div>
            <div class="d-flex justify-content-center">
                <small class="text-muted"> Masz już konto?<a class="ml-2" href="{% url 'login' %}">Zaloguj się</a></small>
            </div>
        </form>
    </div>
</div>
{% endblock content %}