Bombelka/ZaUsmiechBombelka/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from users.forms import MyAuthForm, MyResetForm
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/<username>/', user_views.profile, name='profile'),
    path('profile/edit', user_views.profile_editor, name='profile-editor'),
    path('register/', user_views.register, name='register'),
    path('users/follow/', user_views.user_follow, name='user_follow'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html', authentication_form=MyAuthForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', user_views.MyPasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', user_views.MyPasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('', include('blog.urls')),
    path('market/', include('market.urls')),
    path('actions/', include('actions.urls')),
    path('messages/', include('messanger_system.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bombelka/blog/urls.py
from django.urls import path
from .views import (PostDetailView,
                    PostCreateView,
                    PostUpdateView,
                    PostDeleteView,
                    CommentCreateView)
from . import views

urlpatterns = [
    path('', views.home, name='blog-home'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/<int:pk>/update', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post-delete'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/comment/', CommentCreateView.as_view(), name='add_comment_to_post'),
    path('about/', views.about, name='blog-about'),
    path('likepost/', views.likePost, name='likepost'),
    path('post/<username>/', views.user_posts, name='user-posts'),
]

Bombelka/market/urls.py
from django.urls import path
from . import views
from .views import (ProductCreateView,
                    ProductDetailView,
                    ProductUpdateView,
                    ProductDeleteView,
                    ProductSoldView)

urlpatterns = [
    path('', views.main, name='market-home'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product-detail'),
    path('product/<int:pk>/delete', ProductDeleteView.as_view(), name='product-delete'),
    path('product/<int:pk>/update', ProductUpdateView.as_view(), name='product-update'),
    path('product/<int:pk>/sold', ProductSoldView.as_view(), name='product-sold'),
    path('product/new/', ProductCreateView.as_view(), name='product-create'),
    path('product/<username>/', views.user_products, name='user-products')
]

Bombelka/market/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from PIL import Image
from django.urls import reverse
from django.core.validators import MinValueValidator
from decimal import Decimal

SEX_TAG_CHOISE = [('Boy','Chłopca'),('Girl', 'Dziewczynki'), ('Unisex', 'Zarówno dla chłopca jaki i dziewczynki')]
AGE_TAG_CHOISE = [(1,'< 1 miesiąc'),(2,'< 3 miesiące'),(3,'< 6 miesięcy'),(4,'< 1 rok'),(5,'< 1.5 roku'),(6,'< 2 lata'),(7,'Ponad 2 lata')]

class Product(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=timezone.now)
    title = models.CharField(max_length=100, verbose_name='')
    description = models.TextField(verbose_name='')
    tag_sex = models.CharField(max_length=6, choices = SEX_TAG_CHOISE, default='Unisex', verbose_name='')
    tag_age = models.IntegerField(choices = AGE_TAG_CHOISE, default=1, verbose_name='')
    photo_1 = models.ImageField(default='default_1.jpg', upload_to='product_pics', verbose_name='')
    photo_2 = models.ImageField(default='default_1.jpg', upload_to='product_pics', verbose_name='')
    photo_3 = models.ImageField(default='default_1.jpg', upload_to='product_pics', verbose_name='')
    price = models.DecimalField(decimal_places=2, max_digits=12, validators=[MinValueValidator(Decimal('0.00'))])
    sold = models.BooleanField(default=False)
    sold_for = models.ForeignKey(User, related_name='buyer', null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product-detail', kwargs={'pk': self.pk})

Bombelka/market/views.py
from .models import Product
from actions.utils import create_action
from django import forms
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import (CreateView,
                                ListView,
                                DetailView,
                                UpdateView,
                                DeleteView)
from messanger_system.models import Message
import redis


r=redis.StrictRedis(host=settings.REDIS_HOST,
                    port=settings.REDIS_PORT,
                    db = settings.REDIS_DB)


class ProductCreateView(LoginRequiredMixin,CreateView):
    model = Product
    success_url = '/market'
    fields = ['title', 'description', 'photo_1', 'photo_2', 'photo_3', 'tag_sex','tag_age', 'price']

    def form_valid(self, form):
        form.instance.author = self.request.user
        post = form.save(commit=False)
        post.save()
        create_action(self.request.user, 'dodał produkt', post)
        messages.success(self.request, f'Produkt został dodany')
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['section'] = 'market'
        return context

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        form = super(ProductCreateView, self).get_form(form_class)
        form.fields['description'].widget = forms.Textarea(attrs={"rows":"6", "class":"form-control", "placeholder": "Opis Produktu"})
        form.fields['title'].widget = forms.TextInput(attrs={"class":"form-control",  "placeholder": "Nazwa Produktu"})
        form.fields['price'].widget = forms.NumberInput(attrs={"class":"form-control", "placeholder": "0,00", 'step':".01"})
        form.fields['price'].lable=''
        form.fields['title'].lable=''
        return form


class ProductDeleteView(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
    model = Product
    success_url = '/market'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['section'] = 'market'
        return context

    def test_func(self):
        product = self.get_object()
        if self.request.user == product.author:
            return True
        else:
            return False


class ProductDetailView(LoginRequiredMixin,DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['section'] = 'market'
        product = Product.objects.get(pk=self.kwargs.get('pk'))
        total_views = r.incr('product:{}:views'.format(product.id))
        r.zincrby('product_ranking', 1,  product.id)
        context['total_views'] = total_views
        return context


class ProductSoldView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Product
    template_name = "market/sold_for.html"
    fields = ['sold_for']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.get_object()
        context['section'] = 'market'
        return context

    def get_form(self, form_class=None):
        product = self.get_object()
        messages = Message.objects.filter(Q(subject=product)&Q(parent_msg__isnull=True))
        ids = [1,6]
        sold_id=[]
        for msg in messages:
            sold_id=msg.sender.id
            ids.append(sold_id)

        queryset=User.objects.filter(id__in=sold_id)
        if form_class is None:
            form_class = self.get_form_class()
        form = super(ProductSoldView, self).get_form(form_class)
        form.fields['sold_for'] = forms.ModelChoiceField(queryset=queryset, widget = forms.Select(attrs={'class':"form-control mt-2 mb-2"}))
        form.fields['sold_for'].lable=''
        return form

    def form_valid(self, form):
        form.instance.sold = True
        return super().form_valid(form)

    def test_func(self):
        product = self.get_object()
        if self.request.user == product.author:
            return True
        else:
            return False


class ProductUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Product
    fields = ['title', 'description', 'photo_1', 'photo_2', 'photo_3', 'tag_sex','tag_age', 'price']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['section'] = 'market'
        return context

    def test_func(self):
        product = self.get_object()
        if self.request.user == product.author:
            return True
        else:
            return False


def main(request):
    products = Product.objects.filter(sold=False).order_by('-date_posted')
    paginator = Paginator(products, 3)
    page = request.GET.get('page')

    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            return HttpResponse('')
        products = paginator.page(paginator.num_pages)
    if request.is_ajax():
        return render(request,
                    'market/list_ajax.html',
                    {'products': products,
                    'section': 'market'})

    return render(request,
                    'market/index.html',
                    {'products': products,
                    'section': 'market'})


@login_required
def user_products(request, username):
    user = get_object_or_404(User,
                username=username,
                is_active=True)
    products = Product.objects.filter(author=user).order_by('-date_posted')

    return render(request,
                'market/index.html',
                {'products':products})

Bombelka/market/templates/market/index.html
{% extends "blog/base.html" %}
{% block content %}
<div class="sticky-top">
    <a class="mr-2" href="{% url 'product-create' %}"><button class="btn btn-sample btn-block">Dodaj produkt</button></a>
</div>

<div id="product-list">
    {% include 'market/list_ajax.html' %}
</div>
{% endblock content %}

{% block domready %}
    var page = 1;
    var empty_page = false;
    var block_request = false;

    $(window).scroll(function() {
        var margin = $(document).height() - $(window).height() - 200;
        if  ($(window).scrollTop() > margin && empty_page == false && block_request == false) {
            block_request = true;
            page += 1;
            $.get('?page=' + page, function(data) {
                if(data == '')
                {
                    empty_page = true;
                }
                else {
                    block_request = false;
                    $('#product-list').append(data);
                }
            });
        }
    });

{% endblock %}

Bombelka/market/templates/market/list_ajax.html
{% for product in products %}
<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
            <div class="d-flex align-content-end flex-wrap" >
                <div class="p-2 mr-auto">
                    <img class="rounded-circle article-img" src="{{ product.author.profile.image.url }}">
                </div>
                <div class="p-2 mr-auto">
                    <a class="mr-2" href="{% url 'profile' product.author %}">{{ product.author }}</a>
                    <br>
                    <small class="text-muted mr-2">{{ product.date_posted|date:"d F Y" }}</small>
                </div>
            </div>
            {% if product.author == user %}
            <div class="d-flex bd-highlight" >
                <div class="mr-auto p-2 bd-highlight">
                    <a class="btn btn-danger btn-sm float-right" href="{% url 'product-delete' product.id%}"><span style="font-size:smaller;">Usuń</span></a>
                </div>
                <div class="p-2 bd-highlight">
                    <a class="btn btn-sample btn-sm float-right mr-2" href="{% url 'product-update' product.id%}"><span style="font-size:smaller;">Popraw</span></a>
                </div>
            </div>
            {% endif %}
        </div>
        <br>
        <h2><a class="article-title" href="{% url 'product-detail' product.id %}">{{ product.title }}</a></h2>
        <p class="text-muted">{{product.price}} PLN</p>
         <div class = "row justify-content-center">
            <img class="img-fluid" alt="Responsive image" src="{{ product.photo_1.url }}">
        </div>
        <br>
        {% if product.author == user %}
            <a href="{% url 'product-sold' product.pk%}"><button class="btn btn-sample btn-block">Ustaw jako sprzedane</button></a>
        {% else %}
            <a href="{% url 'messages_compose' product.pk%}"><button class="btn btn-sample btn-block">Skontaktuj się by kupić</button></a>
        {% endif %}
    </div>
</article>
{% endfor %}

Bombelka/market/templates/market/product_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST"  class="d-flex justify-content-center">
            {% csrf_token %}
            <fieldset  class="d-flex justify-content-centerk">
                <h2>Czy chcesz usunąć  produkt z tytułem <i>{{object.title}}</i>?</h2>
                <button class="btn btn-danger btn-block mt-1 mb-1" type="submit">Tak, usuń</button>
                <a class="btn btn-sample btn-block mt-1 mb-1" href="{% url 'product-detail' object.id %}">Nie, porzuć zmiany</a>
                <br>
            </fieldset>
        </form>
        <!-- <button class="btn btn-sample btn-block" href="{% url 'post-detail' object.id %}">Nie, porzuć zmiany</button>
        <br> -->
        <a class="mr-2" href="{% url 'blog-home' %}"><button class="btn btn-outline-info btn-block">Wróć do bloga</button></a>
    </div>
{% endblock content %}

Bombelka/market/templates/market/product_detail.html
{% extends "blog/base.html" %}
{% block content %}
<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
            <div class="d-flex align-content-end flex-wrap" >
                <div class="p-2 mr-auto">
                    <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}">
                </div>
                <div class="p-2 mr-auto">
                    <a class="mr-2" href="{% url 'profile' object.author %}">{{ object.author }}</a>
                    <br>
                    <small class="text-muted mr-2">{{ object.date_posted|date:"d F Y" }}</small>
                </div>
            </div>
            {% if object.author == user %}
            <div class="d-flex bd-highlight" >
                <div class="mr-auto p-2 bd-highlight">
                    <a class="btn btn-danger btn-sm float-right" href="{% url 'product-delete' object.id%}"><span style="font-size:smaller;">Usuń</span></a>
                </div>
                <div class="p-2 bd-highlight">
                    <a class="btn btn-sample btn-sm float-right mr-2" href="{% url 'product-update' object.id%}"><span style="font-size:smaller;">Popraw</span></a>
                </div>
            </div>
            {% endif %}
        </div>
        <h2 class="article-title">{{ object.title }}</h2>
        <div class="d-flex bd-highlight" >
                <div class="mr-auto p-2 bd-highlight">
                    <p class="text-muted">{{object.price}} PLN</p>
                </div>
                <div class="p-2 bd-highlight">
                    <span class="count">
                        <span class="total">{{total_views}}</span> wyświetleń
                     </span>
                </div>
            </div>
        <p>Przeznaczony dla <strong>{{object.get_tag_sex_display}}</strong> w wieku <strong>{{object.get_tag_age_display}}</strong>.</p>
        <div class = "row justify-content-center">
            <img class="img-fluid mb-2" src="{{ object.photo_1.url }}">
        </div>
        <p class="article-content">{{ object.description }}</p>
        <div class="row justify-content-center">
            <div class="col">
            <img class="img-fluid mb-2 mt-2" src="{{ object.photo_2.url }}">
            </div>
            <div class="col">
            <img class="img-fluid mb-2 mt-2" src="{{ object.photo_3.url }}">
            </div>
        </div>
        {% if object.author is user and object.sold is False %}
            <a href="{% url 'product-sold' product.pk%}"><button class="btn btn-sample btn-block">Ustaw jako sprzedane</button></a>
        {% elif object.author is not user and object.sold is False %}
            <a href="{% url 'messages_compose' product.pk%}"><button class="btn btn-sample btn-block">Skontaktuj się by kupić</button></a>
        {% else %}
            <div class="alert alert-success">
                <p>Produkt został sprzedany</p>
            </div>
        {% endif %}
        <a class="mr-2" href="{% url 'market-home' %}"><button class="btn btn-sample btn-block mt-2">Wróć do marketu</button></a>
    </div>
</article>
{% endblock content %}

Bombelka/market/templates/market/product_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags%}
{% block content %}
<form method="POST"  enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="d-flex justify-content-center">Nowy Produkt</legend>
            {{ form.title}}
            <div class="input-group mb-3 mt-3">
                {{ form.price }}
                <div class="input-group-append">
                    <span class="input-group-text" id="basic-addon2">PLN</span>
                </div>
            </div>
            <div class="form-inline ml-1 mb-2 mt-2 mr-1">
                <strong>Poniższe zdjęcie będzie widoczna na stronie głównej marketu {{ form.photo_1|as_crispy_field }}</strong>
            </div>
        <div class="form-inline ml-1 mb-2 mt-4 mr-1">
                Produkt przeznaczony dla <br>{{ form.tag_sex|as_crispy_field }}
        </div>
        <div class="form-inline ml-1 mb-2 mt-2 mr-1">
                w wieku {{ form.tag_age|as_crispy_field }}
        </div>
        <div class="form-row mt-2">
            <div class="form-group col mb-2">
                {{ form.description|as_crispy_field }}
            </div>
        </div>
        <div class="form-inline ml-1 mb-2 mt-2 mr-1">
                <strong>Poniższe zdjęcia będą widoczna na stronie z detalami produktu</strong>
                {{ form.photo_2|as_crispy_field }}
                {{ form.photo_3|as_crispy_field }}
        </div>
        <br>
        <button class="btn btn-sample btn-block" type="submit">Dodaj Produkt</button>
    </fieldset>
</form>


    <!-- <div class="content-section">
        <form method="POST"  enctype="multipart/form-data" class="d-flex justify-content-center">
            {% csrf_token %}
            <fieldset  class="d-flex justify-content-centerk">
                <legend class="d-flex justify-content-center"> Nowy Produkt</legend>
                {{ form.title|as_crispy_field }}
                <p>Poniższe zdjęcie będzie widoczna na stronie głównej marketu</p>
                {{ form.photo_1|as_crispy_field }}
                {{ form.description|as_crispy_field }}
                <button class="btn btn-sample btn-block" type="submit">Publikuj</button>
            </fieldset>
        </form>
        <br>
        <a class="mr-2" href="{% url 'blog-home' %}"><button class="btn btn-outline-info btn-block">Wróć do bloga</button></a>
    </div> -->
{% endblock content %}

Bombelka/market/templates/market/sold_for.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags%}
{% block content %}
<article class="media content-section">
    <div class="media-body">
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <legend class="border-bottom mb-4">Ustaw jako sprzedane</legend>
        <div class="form">
            Jeśli sprzedałeś produkt użytkownikowi z ZaUśmiechBombelka wybierz go z listy by nadal prowadzić z nim konwersacje pieczętując sprzedaż:
            {{ form.sold_for}}
        </div>
    </div>
    <div class="form-group">
        <button class="btn btn-sample btn-block" type="submit">Sprzedaj</button>
    </div>
</form>
<div>
    Jeśli sprzedarz nie dotyczy żadnego z użytkowników z ZaUśmiechBombelka, usuń produkt z witryny.
    <a href="{% url 'product-delete' product.id%}"><button class="btn btn-danger btn-block mt-4">Usuń</button></a>
</div>
</div>
</article>
{% endblock content %}